//provincias argentinas
export const StateArray = [
  { id: "CA", description: "Capital Federal" },
  { id: "BA", description: "Buenos Aires" },
  { id: "CT", description: "Catamarca" },
  { id: "CH", description: "Chaco" },
  { id: "CB", description: "Chubut" },
  { id: "CD", description: "Córdoba" },
  { id: "CR", description: "Corrientes" },
  { id: "ER", description: "Entre Ríos" },
  { id: "FM", description: "Formosa" },
  { id: "JY", description: "Jujuy" },
  { id: "LP", description: "La Pampa" },
  { id: "LR", description: "La Rioja" },
  { id: "MZ", description: "Mendoza" },
  { id: "MN", description: "Misiones" },
  { id: "NQ", description: "Neuquén" },
  { id: "RN", description: "Río Negro" },
  { id: "SA", description: "Salta" },
  { id: "SJ", description: "San Juan" },
  { id: "SL", description: "San Luis" },
  { id: "SC", description: "Santa Cruz" },
  { id: "SF", description: "Santa Fe" },
  { id: "SE", description: "Santiago del Estero" },
  { id: "TF", description: "Tierra del Fuego" },
  { id: "TM", description: "Tucumán" },
];
